version: '2'
services:
  nginx:
    build: .
    container_name: "c_gcp_chacher"
    working_dir: "/etc/nginx/"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx.vh.default.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - BUCKET_NAME=test.v41.me
    # command: >
    #   nginx
    #   -g
    #   "daemon off;"
    command: /bin/sh -c "envsubst '$$BUCKET_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/nginx.vh.conf && nginx -g 'daemon off;'"
    ports:
      - 5555:80